name: Java CI

on:
  push:
    branches: [ "main" ]

jobs:
  cab-book-driver:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cab-book-driver

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Driver Service
        run: mvn clean install

  cab-book-user:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cab-book-user

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build User Service
        run: mvn clean install